//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ClinicaMVC3.Models
{
    public partial class aspnet_Paths
    {
        public aspnet_Paths()
        {
            this.aspnet_PersonalizationPerUser = new HashSet<aspnet_PersonalizationPerUser>();
        }
    
    
    
        #region Primitive Properties
    	[Required(ErrorMessage="Este campo deve ser preenchido.")]
        public System.Guid ApplicationId { get; set; }
    	[Required(ErrorMessage="Este campo deve ser preenchido.")]
        public System.Guid PathId { get; set; }
    	[Required(ErrorMessage="Este campo deve ser preenchido.")]
        [StringLength(256)]
        public string Path { get; set; }
    	[Required(ErrorMessage="Este campo deve ser preenchido.")]
        [StringLength(256)]
        public string LoweredPath { get; set; }

        #endregion
    
    
    
    
        public virtual aspnet_Applications aspnet_Applications { get; set; }
        public virtual aspnet_PersonalizationAllUsers aspnet_PersonalizationAllUsers { get; set; }
        public virtual ICollection<aspnet_PersonalizationPerUser> aspnet_PersonalizationPerUser { get; set; }
    }
    
}
