//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ClinicaMVC3.Models
{
    public partial class aspnet_Users
    {
        public aspnet_Users()
        {
            this.Funcionario = new HashSet<Funcionario>();
            this.aspnet_PersonalizationPerUser = new HashSet<aspnet_PersonalizationPerUser>();
            this.aspnet_Roles = new HashSet<aspnet_Roles>();
        }
    
    
    
        #region Primitive Properties
    	[Required(ErrorMessage="Este campo deve ser preenchido.")]
        public System.Guid ApplicationId { get; set; }
    	[Required(ErrorMessage="Este campo deve ser preenchido.")]
        public System.Guid UserId { get; set; }
    	[Required(ErrorMessage="Este campo deve ser preenchido.")]
        [StringLength(256)]
        public string UserName { get; set; }
    	[Required(ErrorMessage="Este campo deve ser preenchido.")]
        [StringLength(256)]
        public string LoweredUserName { get; set; }
    	//[Required]
        [StringLength(16)]
        public string MobileAlias { get; set; }
    	[Required(ErrorMessage="Este campo deve ser preenchido.")]
        public bool IsAnonymous { get; set; }
    	[Required(ErrorMessage="Este campo deve ser preenchido.")]
        public System.DateTime LastActivityDate { get; set; }

        #endregion
    
    
    
    
        public virtual ICollection<Funcionario> Funcionario { get; set; }
        public virtual aspnet_Membership aspnet_Membership { get; set; }
        public virtual aspnet_Applications aspnet_Applications { get; set; }
        public virtual ICollection<aspnet_PersonalizationPerUser> aspnet_PersonalizationPerUser { get; set; }
        public virtual aspnet_Profile aspnet_Profile { get; set; }
        public virtual ICollection<aspnet_Roles> aspnet_Roles { get; set; }
    }
    
}
