//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ClinicaMVC3.Models
{
    public partial class aspnet_Roles
    {
        public aspnet_Roles()
        {
            this.aspnet_Users = new HashSet<aspnet_Users>();
        }
    
    
    
        #region Primitive Properties
    	[Required(ErrorMessage="Este campo deve ser preenchido.")]
        public System.Guid ApplicationId { get; set; }
    	[Required(ErrorMessage="Este campo deve ser preenchido.")]
        public System.Guid RoleId { get; set; }
    	[Required(ErrorMessage="Este campo deve ser preenchido.")]
        [StringLength(256)]
        public string RoleName { get; set; }
    	[Required(ErrorMessage="Este campo deve ser preenchido.")]
        [StringLength(256)]
        public string LoweredRoleName { get; set; }
    	//[Required]
        [StringLength(256)]
        public string Description { get; set; }

        #endregion
    
    
    
    
        public virtual aspnet_Applications aspnet_Applications { get; set; }
        public virtual ICollection<aspnet_Users> aspnet_Users { get; set; }
    }
    
}
