//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ClinicaMVC3.Models
{
    public partial class aspnet_WebEvent_Events
    {
    
    
        #region Primitive Properties
    	[Required(ErrorMessage="Este campo deve ser preenchido.")]
        [StringLength(32)]
        public string EventId { get; set; }
    	[Required(ErrorMessage="Este campo deve ser preenchido.")]
        public System.DateTime EventTimeUtc { get; set; }
    	[Required(ErrorMessage="Este campo deve ser preenchido.")]
        public System.DateTime EventTime { get; set; }
    	[Required(ErrorMessage="Este campo deve ser preenchido.")]
        [StringLength(256)]
        public string EventType { get; set; }
    	[Required(ErrorMessage="Este campo deve ser preenchido.")]
        public decimal EventSequence { get; set; }
    	[Required(ErrorMessage="Este campo deve ser preenchido.")]
        public decimal EventOccurrence { get; set; }
    	[Required(ErrorMessage="Este campo deve ser preenchido.")]
        public int EventCode { get; set; }
    	[Required(ErrorMessage="Este campo deve ser preenchido.")]
        public int EventDetailCode { get; set; }
    	//[Required]
        [StringLength(1024)]
        public string Message { get; set; }
    	//[Required]
        [StringLength(256)]
        public string ApplicationPath { get; set; }
    	//[Required]
        [StringLength(256)]
        public string ApplicationVirtualPath { get; set; }
    	[Required(ErrorMessage="Este campo deve ser preenchido.")]
        [StringLength(256)]
        public string MachineName { get; set; }
    	//[Required]
        [StringLength(1024)]
        public string RequestUrl { get; set; }
    	//[Required]
        [StringLength(256)]
        public string ExceptionType { get; set; }
    	//[Required]
        [StringLength(1073741823)]
        public string Details { get; set; }

        #endregion
    
    
    
    }
    
}
