//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ClinicaMVC3.Models
{
    public partial class aspnet_Membership
    {
    
    
        #region Primitive Properties
    	[Required(ErrorMessage="Este campo deve ser preenchido.")]
        public System.Guid ApplicationId { get; set; }
    	[Required(ErrorMessage="Este campo deve ser preenchido.")]
        public System.Guid UserId { get; set; }
    	[Required(ErrorMessage="Este campo deve ser preenchido.")]
        [StringLength(128)]
        public string Password { get; set; }
    	[Required(ErrorMessage="Este campo deve ser preenchido.")]
        public int PasswordFormat { get; set; }
    	[Required(ErrorMessage="Este campo deve ser preenchido.")]
        [StringLength(128)]
        public string PasswordSalt { get; set; }
    	//[Required]
        [StringLength(16)]
        public string MobilePIN { get; set; }
    	//[Required]
        [StringLength(256)]
        public string Email { get; set; }
    	//[Required]
        [StringLength(256)]
        public string LoweredEmail { get; set; }
    	//[Required]
        [StringLength(256)]
        public string PasswordQuestion { get; set; }
    	//[Required]
        [StringLength(128)]
        public string PasswordAnswer { get; set; }
    	[Required(ErrorMessage="Este campo deve ser preenchido.")]
        public bool IsApproved { get; set; }
    	[Required(ErrorMessage="Este campo deve ser preenchido.")]
        public bool IsLockedOut { get; set; }
    	[Required(ErrorMessage="Este campo deve ser preenchido.")]
        public System.DateTime CreateDate { get; set; }
    	[Required(ErrorMessage="Este campo deve ser preenchido.")]
        public System.DateTime LastLoginDate { get; set; }
    	[Required(ErrorMessage="Este campo deve ser preenchido.")]
        public System.DateTime LastPasswordChangedDate { get; set; }
    	[Required(ErrorMessage="Este campo deve ser preenchido.")]
        public System.DateTime LastLockoutDate { get; set; }
    	[Required(ErrorMessage="Este campo deve ser preenchido.")]
        public int FailedPasswordAttemptCount { get; set; }
    	[Required(ErrorMessage="Este campo deve ser preenchido.")]
        public System.DateTime FailedPasswordAttemptWindowStart { get; set; }
    	[Required(ErrorMessage="Este campo deve ser preenchido.")]
        public int FailedPasswordAnswerAttemptCount { get; set; }
    	[Required(ErrorMessage="Este campo deve ser preenchido.")]
        public System.DateTime FailedPasswordAnswerAttemptWindowStart { get; set; }
    	//[Required]
        [StringLength(1073741823)]
        public string Comment { get; set; }

        #endregion
    
    
    
    
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual aspnet_Applications aspnet_Applications { get; set; }
    }
    
}
