//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ClinicaMVC3.Models;
using System.Data;
using System.Web.Security;
using ClinicaMVC3.Controllers;


namespace ClinicaMVC3.Models
{
    public partial class Telefone
    {

        public static List<SelectListItem> SelectListTelefones(ClinicaEntities db)
        {
            Array enums = Enum.GetValues(typeof(ClinicaMVC3.Models.Telefone.tipoTelefone));
            List<SelectListItem> selectList = new List<SelectListItem>();
            foreach (var telefone in db.Telefone.ToList())
            {
                selectList.Add(new SelectListItem()
                {
                    Value = telefone.TelefoneId.ToString(),
                    Text = telefone.Numero,
                    Selected = false
                });
            }
            return selectList;
        }

        public enum tipoTelefone
        {
            Celular = 1 ,
            Telefone= 2
        }

        public Telefone()
        {
            this.FuncionarioTelefone = new HashSet<FuncionarioTelefone>();
            this.PacienteTelefone = new HashSet<PacienteTelefone>();
        }
    
    
    
        #region Primitive Properties
    	[Required(ErrorMessage="Este campo deve ser preenchido.")]
        public int TelefoneId { get; set; }
    	[Required(ErrorMessage="Este campo deve ser preenchido.")]
        [StringLength(15)]
        public string Numero { get; set; }
    	[Required(ErrorMessage="Este campo deve ser preenchido.")]
        public int Tipo { get; set; }

        #endregion
    
    
    
    
        public virtual ICollection<FuncionarioTelefone> FuncionarioTelefone { get; set; }
        public virtual ICollection<PacienteTelefone> PacienteTelefone { get; set; }
    }
    
}
