//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ClinicaMVC.Models
{
    public partial class PacienteTelefone
    {
    
    
        #region Primitive Properties
    	[Required(ErrorMessage="Este campo deve ser preenchido.")]
        public int PacienteTelefoneId { get; set; }
    	[Required(ErrorMessage="Este campo deve ser preenchido.")]
        public int PacienteId { get; set; }
    	[Required(ErrorMessage="Este campo deve ser preenchido.")]
        public int TelefoneId { get; set; }

        #endregion
    
    
    
    
        public virtual Paciente Paciente { get; set; }
        public virtual Telefone Telefone { get; set; }
    }
    
}
