//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ClinicaMVC3.Models
{
    public partial class aspnet_PersonalizationPerUser
    {
    
    
        #region Primitive Properties
    	[Required(ErrorMessage="Este campo deve ser preenchido.")]
        public System.Guid Id { get; set; }
    	//[Required]
        public Nullable<System.Guid> PathId { get; set; }
    	//[Required]
        public Nullable<System.Guid> UserId { get; set; }
    	[Required(ErrorMessage="Este campo deve ser preenchido.")]
        public byte[] PageSettings { get; set; }
    	[Required(ErrorMessage="Este campo deve ser preenchido.")]
        public System.DateTime LastUpdatedDate { get; set; }

        #endregion
    
    
    
    
        public virtual aspnet_Paths aspnet_Paths { get; set; }
        public virtual aspnet_Users aspnet_Users { get; set; }
    }
    
}
