//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace ClinicaMVC3.Models
{
    public partial class ClinicaEntities : DbContext
    {
        public ClinicaEntities()
            : base("name=ClinicaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Consulta> Consulta { get; set; }
        public DbSet<Especialidade> Especialidade { get; set; }
        public DbSet<Funcionario> Funcionario { get; set; }
        public DbSet<FuncionarioEspecialidade> FuncionarioEspecialidade { get; set; }
        public DbSet<FuncionarioTelefone> FuncionarioTelefone { get; set; }
        public DbSet<Paciente> Paciente { get; set; }
        public DbSet<PacienteTelefone> PacienteTelefone { get; set; }
        public DbSet<Telefone> Telefone { get; set; }
        public DbSet<PlanoSaude> PlanoSaude { get; set; }
        public DbSet<aspnet_Users> aspnet_Users { get; set; }
        public DbSet<aspnet_Membership> aspnet_Membership { get; set; }
    }
}
