//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ClinicaMVC3.Models
{
    public partial class Funcionario
    {
        public Funcionario()
        {
            this.Consulta = new HashSet<Consulta>();
            this.FuncionarioEspecialidade = new HashSet<FuncionarioEspecialidade>();
            this.FuncionarioTelefone = new HashSet<FuncionarioTelefone>();
        }
    
    
    
        #region Primitive Properties
    	[Required(ErrorMessage="Este campo deve ser preenchido.")]
        public int FuncionarioId { get; set; }
    	[Required(ErrorMessage="Este campo deve ser preenchido.")]
        [StringLength(100)]
        public string Nome { get; set; }
    	[Required(ErrorMessage="Este campo deve ser preenchido.")]
        [StringLength(11)]
        public string RG { get; set; }
    	[Required(ErrorMessage="Este campo deve ser preenchido.")]
        public System.Guid UserId { get; set; }
    	[Required(ErrorMessage="Este campo deve ser preenchido.")]
        [StringLength(150)]
        public string endereco { get; set; }
    	[Required(ErrorMessage="Este campo deve ser preenchido.")]
        public int funcao { get; set; }

        #endregion
    
    
    
    
        public virtual ICollection<Consulta> Consulta { get; set; }
        public virtual ICollection<FuncionarioEspecialidade> FuncionarioEspecialidade { get; set; }
        public virtual ICollection<FuncionarioTelefone> FuncionarioTelefone { get; set; }
        public virtual aspnet_Users aspnet_Users { get; set; }
    }
    
}
