//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ClinicaMVC3.Models
{
    public partial class Paciente
    {
        public Paciente()
        {
            this.Consulta = new HashSet<Consulta>();
            this.PacienteTelefone = new HashSet<PacienteTelefone>();
        }
    
    
    
        #region Primitive Properties
    	[Required(ErrorMessage="Este campo deve ser preenchido.")]
        public int PacienteId { get; set; }

    	[Required(ErrorMessage="Este campo deve ser preenchido.")]
        [MaxLength(45)]
        public string Nome { get; set; }

    	[Required(ErrorMessage="Este campo deve ser preenchido.")]
        [MaxLength(100)]
        [Display(Name = "Endereço")]
        public string Endereco { get; set; }

    	
        [MaxLength(100)]
        [Display(Name = "Observações do médico")]
        public string ObservacaoMedico { get; set; }

        #endregion
    
    
    
    
        public virtual ICollection<Consulta> Consulta { get; set; }
        public virtual ICollection<PacienteTelefone> PacienteTelefone { get; set; }
    }
    
}
